# Generated by Django 6.0.1 on 2026-01-11 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='TravelUz', max_length=100, verbose_name='Sayt nomi')),
                ('director_name', models.CharField(max_length=100, verbose_name='Direktor F.I.O')),
                ('director_image', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Direktor rasmi')),
                ('address_uz', models.CharField(max_length=255, verbose_name='Manzil (UZ)')),
                ('address_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil (RU)')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('stir', models.CharField(max_length=20, verbose_name='STIR (INN)')),
                ('license_number', models.CharField(default='Jarayonda', max_length=50, verbose_name='Litsenziya raqami')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram link')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram link')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook link')),
            ],
            options={
                'verbose_name': "Kompaniya ma'lumoti",
                'verbose_name_plural': "Kompaniya ma'lumotlari",
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=255, verbose_name='Tur nomi (UZ)')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tur nomi (RU)')),
                ('description_uz', models.TextField(verbose_name='Tavsif (UZ)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Tavsif (RU)')),
                ('category', models.CharField(choices=[('ziyorat', 'Ziyorat'), ('europe', 'Yevropa'), ('sea', "Dengiz bo'yi"), ('visa', 'Viza xizmati')], default='ziyorat', max_length=50, verbose_name='Kategoriya')),
                ('price', models.CharField(help_text="Masalan: $590 yoki 7 mln so'm", max_length=100, verbose_name='Narxi')),
                ('duration_uz', models.CharField(help_text='Masalan: 7 kun / 6 kecha', max_length=100, verbose_name='Davomiyligi (UZ)')),
                ('duration_ru', models.CharField(blank=True, max_length=100, null=True, verbose_name='Davomiyligi (RU)')),
                ('image', models.ImageField(upload_to='tours/', verbose_name='Asosiy rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name="Saytda ko'rinsinmi?")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sayohat',
                'verbose_name_plural': 'Sayohatlar',
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Xabar')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('contacted', "Bog'lanildi"), ('finished', 'Yakunlandi'), ('cancelled', 'Bekor qilindi')], default='new', max_length=20, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kelib tushgan vaqti')),
                ('tour', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tour', verbose_name="Qaysi tur bo'yicha")),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
            },
        ),
    ]
